version: '3'
services:
  todo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - REACT_APP_API_URL=http://localhost:4000
